// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-l2Ofa5lHr-Ylbk2uyqMCVUG4l6RmncY',
    appId: '1:351226344161:web:3e1665c740cfd33d2afda0',
    messagingSenderId: '351226344161',
    projectId: 'testproject-4cd35',
    authDomain: 'testproject-4cd35.firebaseapp.com',
    storageBucket: 'testproject-4cd35.appspot.com',
    measurementId: 'G-GR600PQK98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_994FS9fnY57QP4exvDdo-xAhUEjZik',
    appId: '1:351226344161:android:61fbc1049b71b6e02afda0',
    messagingSenderId: '351226344161',
    projectId: 'testproject-4cd35',
    storageBucket: 'testproject-4cd35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ynzL4zO5DaAiEp80dr_HZAR2_Oecmbo',
    appId: '1:351226344161:ios:bf77055aa95063732afda0',
    messagingSenderId: '351226344161',
    projectId: 'testproject-4cd35',
    storageBucket: 'testproject-4cd35.appspot.com',
    iosClientId: '351226344161-pobfila0kuf4eel4cb6orqqp24rd96g7.apps.googleusercontent.com',
    iosBundleId: 'com.videomonster.testapp',
  );
}
